# -*- coding: utf-8 -*-
"""Par ou Ímpar

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19Uzka5GoC7_-FVHIYuGFEjZpBtcHn-D4
"""

# 1- Defina quem serão os jogadores.
# 2- Definir quem escolhe primeiro.
# 3- Definir a escolha entre Par ou ímpar.
# 4- Coletar os números escolhidos pelos jogadores.
# 5- Calcular a soma dos números.
# 6- Informar o ganhador

p1 =input('Digite o nome do primeiro player: ')
p2 =input('Digite o nome do segundo player: ')
print(' Quem escolhe  primeiro {} ou {} ??'.format(p1, p2))
primeiro_jogador = input(' Digite 1 para escolher {} ou 2 para escolher {} '.format(p1 ,p2))
segundo_jogador  = p2

if primeiro_jogador == "1":
  primeiro_jogador = p1
if segundo_jogador == p2:
  if primeiro_jogador == "2":
    primeiro_jogador = p2
    segundo_jogador = p1

print(' Digite 0 para escolher Par ou 1 para escolher ímpar')
escolha =input('{} Você escolhe entre ÍMPAR ou PAR '.format(primeiro_jogador))
escolha2 = segundo_jogador

if escolha == 'ímpar' or escolha == 'impar' or escolha == '1':
  if escolha == 'ímpar':
    pass
  if escolha2 == 'par':
    pass
elif escolha == 'par' or escolha == '0':
  escolha = 'par'
  escolha2 = 'ímpar'
print(' {} jogador você ficou com a {} e o {} ficou com a {}.'.format(segundo_jogador, escolha2, primeiro_jogador, escolha))

numero1 = int(input(' {} digite um número '.format(primeiro_jogador)))
numero2 = int(input(' {} digite um número '.format(segundo_jogador)))

soma = numero1 + numero2
if soma % 2 == 0:
   vencedor = 'par'
else:
   vencedor ='ímpar'

if vencedor == escolha:
   print('{} ganhou !!'.format(primeiro_jogador))
else:
   print('{} ganhou !!'.format(segundo_jogador))

